services:
  dfd:
    build:
      target: production
      args:
        SQLITE_FILE: /mnt/data/dfd.sqlite
    volumes:
      - ${DFD_DATA_DIR}:/mnt/data:rw
    ports:
      - "${DFD_HOST}:${DFD_PORT}:3000"
    environment:
      SQLITE_FILE: /mnt/data/dfd.sqlite
    command: node build
