services:
  dfd:
    build:
      target: production
    volumes:
      - ${DFD_DATA_DIR}:/mnt/data:rw
    ports:
      - "${DFD_HOST}:${DFD_PORT}:3000"
    environment:
      DATABASE_URL: /mnt/data/dfd.sqlite
    command: node build
