services:
  migrate:
    build:
      target: migration
    volumes:
      - ${DFD_DATA_DIR}:/mnt/data:rw
    environment:
      DATABASE_URL: /mnt/data/dfd.sqlite
    command: node drizzle
  dfd:
    build:
      target: server
    depends_on:
      - migrate
    volumes:
      - ${DFD_DATA_DIR}:/mnt/data:rw
    ports:
      - "${DFD_HOST}:${DFD_PORT}:3000"
    environment:
      DATABASE_URL: /mnt/data/dfd.sqlite
    logging:
      driver: syslog
      options:
        tag: dfd-dfd
    command: node build
